name: Build and Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'  # Запуск при пуше нового тега (например, v1.0.0)

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build solution
        run: |
          msbuild.exe Backup1C.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build-Artifacts
          path: Backup1C/bin/Release/*.exe  # Путь до собранного .exe файла

  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: Build-Artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Backup1C/bin/Release/Backup1C.exe  # Путь до .exe файла
          asset_name: Backup1C.exe
          asset_content_type: application/octet-stream
